global using BeamOs.Common.Contracts;
global using BeamOs.StructuralAnalysis.Contracts.Common;
global using BeamOs.StructuralAnalysis.Contracts.PhysicalModel.LoadCases;
global using BeamOs.StructuralAnalysis.Contracts.PhysicalModel.LoadCombinations;
global using ResultOfAnalyticalResultsResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.AnalyticalResults.Diagrams.AnalyticalResultsResponse>;
global using ResultOfBatchResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Nodes.BatchResponse>;
global using ResultOfBeamOsModelBuilderDto = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.Common.BeamOsModelBuilderDto>;
global using ResultOfboolean = BeamOs.Common.Contracts.Result<bool>;
global using ResultOfDiagramResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.AnalyticalResults.Diagrams.AnalyticalResultsResponse>;
global using ResultOfElement1dResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Element1ds.Element1dResponse>;
global using ResultOfint = BeamOs.Common.Contracts.Result<int>;
global using ResultOfListOfModelInfoResponse = BeamOs.Common.Contracts.Result<System.Collections.Generic.List<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Models.ModelInfoResponse>>;
global using ResultOfLoadCase = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.LoadCases.LoadCase>;
global using ResultOfLoadCombination = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.LoadCombinations.LoadCombination>;
global using ResultOfMaterialResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Materials.MaterialResponse>;
global using ResultOfModelEntityResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.Common.ModelEntityResponse>;
global using ResultOfModelResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Models.ModelResponse>;
global using ResultOfModelResponseHydrated = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Models.ModelResponseHydrated>;
global using ResultOfMomentLoadResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.MomentLoads.MomentLoadResponse>;
global using ResultOfNodeResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Nodes.NodeResponse>;
global using ResultOfNodeResultResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.AnalyticalResults.NodeResult.NodeResultResponse>;
global using ResultOfPointLoadResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.PointLoads.PointLoadResponse>;
global using ResultOfResultSetResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.AnalyticalResults.ResultSetResponse>;
global using ResultOfSectionProfileFromLibrary = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.SectionProfiles.SectionProfileFromLibrary>;
global using ResultOfSectionProfileResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.SectionProfiles.SectionProfileResponse>;
global using ResultOfstring = BeamOs.Common.Contracts.Result<string>;
global using SectionProfileFromLibraryData2 = BeamOs.StructuralAnalysis.Contracts.PhysicalModel.SectionProfiles.SectionProfileFromLibraryData;
