global using BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Element1d;
global using BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Material;
global using BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Model;
global using BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Node;
global using BeamOs.StructuralAnalysis.Contracts.PhysicalModel.PointLoad;
global using BeamOs.StructuralAnalysis.Contracts.PhysicalModel.SectionProfile;
global using ResultOfboolean = BeamOs.Common.Contracts.Result<bool>;
global using ResultOfElement1dResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Element1d.Element1dResponse>;
global using ResultOfint = BeamOs.Common.Contracts.Result<int>;
global using ResultOfMaterialResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Material.MaterialResponse>;
global using ResultOfModelResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Model.ModelResponse>;
global using ResultOfNodeResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.Node.NodeResponse>;
global using ResultOfNodeResultResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.AnalyticalResults.NodeResult.NodeResultResponse>;
global using ResultOfPointLoadResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.PointLoad.PointLoadResponse>;
global using ResultOfSectionProfileResponse = BeamOs.Common.Contracts.Result<BeamOs.StructuralAnalysis.Contracts.PhysicalModel.SectionProfile.SectionProfileResponse>;
