/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiUsersById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiModels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{modelId}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiModelsByModelIdNodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{modelId}/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchApiModelsByModelIdNodesByNodeId"];
        trace?: never;
    };
    "/api/models/{modelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchApiModelsByModelId"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    getApiUsersById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                    };
                };
            };
        };
    };
    postApiModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: uuid */
                    authorId: string;
                    message: string;
                };
                "application/x-www-form-urlencoded": {
                    name: string;
                    /** Format: uuid */
                    authorId: string;
                    message: string;
                };
                "multipart/form-data": {
                    name: string;
                    /** Format: uuid */
                    authorId: string;
                    message: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        model: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                        };
                        version: {
                            /** Format: uuid */
                            modelId: string;
                            branchName: string;
                            /** Format: uuid */
                            revisionId: string;
                            /** @description Number of revisions ahead of the parent branch. In progress revisions are not included in the number */
                            revisionsAhead: number;
                            revisionsBehind: number;
                            /** Format: uuid */
                            inProgressRevisionId: string;
                        };
                    };
                };
            };
        };
    };
    postApiModelsByModelIdNodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    nodeId: string;
                    name: string;
                    target: {
                        /** Format: uuid */
                        revisionId?: string;
                        /** Format: uuid */
                        draftId?: string;
                    };
                };
                "application/x-www-form-urlencoded": {
                    /** Format: uuid */
                    nodeId: string;
                    name: string;
                    target: {
                        /** Format: uuid */
                        revisionId?: string;
                        /** Format: uuid */
                        draftId?: string;
                    };
                };
                "multipart/form-data": {
                    /** Format: uuid */
                    nodeId: string;
                    name: string;
                    target: {
                        /** Format: uuid */
                        revisionId?: string;
                        /** Format: uuid */
                        draftId?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        node: {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            modelId: string;
                            name: string;
                        };
                        version: {
                            /** Format: uuid */
                            modelId: string;
                            /** Format: uuid */
                            revisionId: string | null;
                            /** Format: uuid */
                            draftId: string | null;
                        };
                    };
                };
            };
        };
    };
    patchApiModelsByModelIdNodesByNodeId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    target: {
                        /** Format: uuid */
                        revisionId?: string;
                        /** Format: uuid */
                        draftId?: string;
                    };
                };
                "application/x-www-form-urlencoded": {
                    name: string;
                    target: {
                        /** Format: uuid */
                        revisionId?: string;
                        /** Format: uuid */
                        draftId?: string;
                    };
                };
                "multipart/form-data": {
                    name: string;
                    target: {
                        /** Format: uuid */
                        revisionId?: string;
                        /** Format: uuid */
                        draftId?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        node: {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            modelId: string;
                            name: string;
                        };
                        version: {
                            /** Format: uuid */
                            modelId: string;
                            /** Format: uuid */
                            revisionId: string | null;
                            /** Format: uuid */
                            draftId: string | null;
                        };
                    };
                };
            };
        };
    };
    patchApiModelsByModelId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    target: {
                        /** Format: uuid */
                        revisionId?: string;
                        /** Format: uuid */
                        draftId?: string;
                    };
                };
                "application/x-www-form-urlencoded": {
                    name: string;
                    target: {
                        /** Format: uuid */
                        revisionId?: string;
                        /** Format: uuid */
                        draftId?: string;
                    };
                };
                "multipart/form-data": {
                    name: string;
                    target: {
                        /** Format: uuid */
                        revisionId?: string;
                        /** Format: uuid */
                        draftId?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        model: {
                            /** Format: uuid */
                            id: string;
                            name: string;
                        };
                        version: {
                            /** Format: uuid */
                            modelId: string;
                            /** Format: uuid */
                            revisionId: string | null;
                            /** Format: uuid */
                            draftId: string | null;
                        };
                    };
                };
            };
        };
    };
}
