//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IApiAlphaClient {

    /**
     * @return Success
     */
    runDirectStiffnessMethod(idRequest: IdRequest): Promise<AnalyticalModelResponse3>;

    /**
     * @return Success
     */
    createSectionProfile(createSectionProfileRequest: CreateSectionProfileRequest): Promise<SectionProfileResponse>;

    /**
     * @return Success
     */
    createPointLoad(createPointLoadRequest: CreatePointLoadRequest): Promise<PointLoadResponse>;

    /**
     * @return Success
     */
    createMomentLoad(createMomentLoadRequest: CreateMomentLoadRequest): Promise<MomentLoadResponse>;

    /**
     * @return Success
     */
    getMomentLoads(): Promise<MomentLoadResponse[]>;

    /**
     * @return Success
     */
    createModel(createModelRequest: CreateModelRequest): Promise<ModelResponse>;

    /**
     * @return Success
     */
    deleteModel(id: string | null): Promise<boolean>;

    /**
     * @param properties (optional) 
     * @return Success
     */
    getModel(id: string | null, properties: string[] | null | undefined): Promise<ModelResponse>;

    /**
     * @param units (optional) 
     * @return Success
     */
    getModelHydrated(modelId: string | null, units: PreconfiguredUnits | null | undefined): Promise<ModelResponseHydrated>;

    /**
     * @return Success
     */
    createMaterial(createMaterialRequest: CreateMaterialRequest): Promise<MaterialResponse>;

    /**
     * @param nodeIds (optional) 
     * @return Success
     */
    getNodeResults(modelId: string | null, nodeIds: string[] | null | undefined): Promise<NodeResultResponse[]>;

    /**
     * @return Success
     */
    createNode(createNodeRequest: CreateNodeRequest): Promise<NodeResponse>;

    /**
     * @return Success
     */
    getSingleNode(id: string | null): Promise<NodeResponse>;

    /**
     * @return Success
     */
    getShearDiagram(id: string | null): Promise<ShearDiagramResponse>;

    /**
     * @return Success
     */
    createElement1d(createElement1dRequest: CreateElement1dRequest): Promise<Element1DResponse>;

    /**
     * @return Success
     */
    getElement1ds(): Promise<Element1DResponse[]>;

    /**
     * @return Success
     */
    getSingleElement1d(id: string | null): Promise<Element1DResponse>;
}

export class ApiAlphaClient implements IApiAlphaClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return Success
     */
    runDirectStiffnessMethod(idRequest: IdRequest): Promise<AnalyticalModelResponse3> {
        let url_ = this.baseUrl + "/api/direct-stiffness-method/run/";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(idRequest);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRunDirectStiffnessMethod(_response);
        });
    }

    protected processRunDirectStiffnessMethod(response: Response): Promise<AnalyticalModelResponse3> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AnalyticalModelResponse3.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AnalyticalModelResponse3>(null as any);
    }

    /**
     * @return Success
     */
    createSectionProfile(createSectionProfileRequest: CreateSectionProfileRequest): Promise<SectionProfileResponse> {
        let url_ = this.baseUrl + "/api/SectionProfiles";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(createSectionProfileRequest);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateSectionProfile(_response);
        });
    }

    protected processCreateSectionProfile(response: Response): Promise<SectionProfileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SectionProfileResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SectionProfileResponse>(null as any);
    }

    /**
     * @return Success
     */
    createPointLoad(createPointLoadRequest: CreatePointLoadRequest): Promise<PointLoadResponse> {
        let url_ = this.baseUrl + "/api/point-load";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(createPointLoadRequest);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreatePointLoad(_response);
        });
    }

    protected processCreatePointLoad(response: Response): Promise<PointLoadResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = PointLoadResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PointLoadResponse>(null as any);
    }

    /**
     * @return Success
     */
    createMomentLoad(createMomentLoadRequest: CreateMomentLoadRequest): Promise<MomentLoadResponse> {
        let url_ = this.baseUrl + "/api/moment-loads";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(createMomentLoadRequest);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateMomentLoad(_response);
        });
    }

    protected processCreateMomentLoad(response: Response): Promise<MomentLoadResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = MomentLoadResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MomentLoadResponse>(null as any);
    }

    /**
     * @return Success
     */
    getMomentLoads(): Promise<MomentLoadResponse[]> {
        let url_ = this.baseUrl + "/api/moment-loads";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetMomentLoads(_response);
        });
    }

    protected processGetMomentLoads(response: Response): Promise<MomentLoadResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(MomentLoadResponse.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MomentLoadResponse[]>(null as any);
    }

    /**
     * @return Success
     */
    createModel(createModelRequest: CreateModelRequest): Promise<ModelResponse> {
        let url_ = this.baseUrl + "/api/models";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(createModelRequest);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateModel(_response);
        });
    }

    protected processCreateModel(response: Response): Promise<ModelResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ModelResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ModelResponse>(null as any);
    }

    /**
     * @return Success
     */
    deleteModel(id: string | null): Promise<boolean> {
        let url_ = this.baseUrl + "/api/models/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteModel(_response);
        });
    }

    protected processDeleteModel(response: Response): Promise<boolean> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<boolean>(null as any);
    }

    /**
     * @param properties (optional) 
     * @return Success
     */
    getModel(id: string | null, properties: string[] | null | undefined): Promise<ModelResponse> {
        let url_ = this.baseUrl + "/api/models/{id}?";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (properties !== undefined && properties !== null)
            properties && properties.forEach(item => { url_ += "properties=" + encodeURIComponent("" + item) + "&"; });
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetModel(_response);
        });
    }

    protected processGetModel(response: Response): Promise<ModelResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ModelResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ModelResponse>(null as any);
    }

    /**
     * @param units (optional) 
     * @return Success
     */
    getModelHydrated(modelId: string | null, units: PreconfiguredUnits | null | undefined): Promise<ModelResponseHydrated> {
        let url_ = this.baseUrl + "/api/models/{modelId}/hydrated?";
        if (modelId === undefined || modelId === null)
            throw new Error("The parameter 'modelId' must be defined.");
        url_ = url_.replace("{modelId}", encodeURIComponent("" + modelId));
        if (units !== undefined && units !== null)
            url_ += "units=" + encodeURIComponent("" + units) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetModelHydrated(_response);
        });
    }

    protected processGetModelHydrated(response: Response): Promise<ModelResponseHydrated> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ModelResponseHydrated.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ModelResponseHydrated>(null as any);
    }

    /**
     * @return Success
     */
    createMaterial(createMaterialRequest: CreateMaterialRequest): Promise<MaterialResponse> {
        let url_ = this.baseUrl + "/api/materials";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(createMaterialRequest);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateMaterial(_response);
        });
    }

    protected processCreateMaterial(response: Response): Promise<MaterialResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = MaterialResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MaterialResponse>(null as any);
    }

    /**
     * @param nodeIds (optional) 
     * @return Success
     */
    getNodeResults(modelId: string | null, nodeIds: string[] | null | undefined): Promise<NodeResultResponse[]> {
        let url_ = this.baseUrl + "/api/node-results/{modelId}?";
        if (modelId === undefined || modelId === null)
            throw new Error("The parameter 'modelId' must be defined.");
        url_ = url_.replace("{modelId}", encodeURIComponent("" + modelId));
        if (nodeIds !== undefined && nodeIds !== null)
            nodeIds && nodeIds.forEach(item => { url_ += "nodeIds=" + encodeURIComponent("" + item) + "&"; });
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetNodeResults(_response);
        });
    }

    protected processGetNodeResults(response: Response): Promise<NodeResultResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(NodeResultResponse.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<NodeResultResponse[]>(null as any);
    }

    /**
     * @return Success
     */
    createNode(createNodeRequest: CreateNodeRequest): Promise<NodeResponse> {
        let url_ = this.baseUrl + "/api/nodes";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(createNodeRequest);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateNode(_response);
        });
    }

    protected processCreateNode(response: Response): Promise<NodeResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = NodeResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<NodeResponse>(null as any);
    }

    /**
     * @return Success
     */
    getSingleNode(id: string | null): Promise<NodeResponse> {
        let url_ = this.baseUrl + "/api/nodes/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetSingleNode(_response);
        });
    }

    protected processGetSingleNode(response: Response): Promise<NodeResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = NodeResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<NodeResponse>(null as any);
    }

    /**
     * @return Success
     */
    getShearDiagram(id: string | null): Promise<ShearDiagramResponse> {
        let url_ = this.baseUrl + "/api/element1Ds/{id}/diagrams/shear/";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetShearDiagram(_response);
        });
    }

    protected processGetShearDiagram(response: Response): Promise<ShearDiagramResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ShearDiagramResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ShearDiagramResponse>(null as any);
    }

    /**
     * @return Success
     */
    createElement1d(createElement1dRequest: CreateElement1dRequest): Promise<Element1DResponse> {
        let url_ = this.baseUrl + "/api/element1Ds";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(createElement1dRequest);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateElement1d(_response);
        });
    }

    protected processCreateElement1d(response: Response): Promise<Element1DResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = Element1DResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Element1DResponse>(null as any);
    }

    /**
     * @return Success
     */
    getElement1ds(): Promise<Element1DResponse[]> {
        let url_ = this.baseUrl + "/api/element1Ds";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetElement1ds(_response);
        });
    }

    protected processGetElement1ds(response: Response): Promise<Element1DResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(Element1DResponse.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Element1DResponse[]>(null as any);
    }

    /**
     * @return Success
     */
    getSingleElement1d(id: string | null): Promise<Element1DResponse> {
        let url_ = this.baseUrl + "/api/element1Ds/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetSingleElement1d(_response);
        });
    }

    protected processGetSingleElement1d(response: Response): Promise<Element1DResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = Element1DResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Element1DResponse>(null as any);
    }
}

export class AnalyticalModelResponse3 implements IAnalyticalModelResponse3 {
    nodeResponses!: NodeResultResponse[];

    constructor(data?: IAnalyticalModelResponse3) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.nodeResponses = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["nodeResponses"])) {
                this.nodeResponses = [] as any;
                for (let item of _data["nodeResponses"])
                    this.nodeResponses!.push(NodeResultResponse.fromJS(item));
            }
        }
    }

    static fromJS(data: any): AnalyticalModelResponse3 {
        data = typeof data === 'object' ? data : {};
        let result = new AnalyticalModelResponse3();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.nodeResponses)) {
            data["nodeResponses"] = [];
            for (let item of this.nodeResponses)
                data["nodeResponses"].push(item.toJSON());
        }
        return data;
    }
}

export interface IAnalyticalModelResponse3 {
    nodeResponses: NodeResultResponse[];
}

export abstract class BeamOsContractBase implements IBeamOsContractBase {

    constructor(data?: IBeamOsContractBase) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): BeamOsContractBase {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'BeamOsContractBase' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IBeamOsContractBase {
}

export class NodeResultResponse extends BeamOsContractBase implements INodeResultResponse {
    nodeId!: string;
    forces!: ForcesResponse;
    displacements!: DisplacementsResponse;

    constructor(data?: INodeResultResponse) {
        super(data);
        if (!data) {
            this.forces = new ForcesResponse();
            this.displacements = new DisplacementsResponse();
        }
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.nodeId = _data["nodeId"];
            this.forces = _data["forces"] ? ForcesResponse.fromJS(_data["forces"]) : new ForcesResponse();
            this.displacements = _data["displacements"] ? DisplacementsResponse.fromJS(_data["displacements"]) : new DisplacementsResponse();
        }
    }

    static fromJS(data: any): NodeResultResponse {
        data = typeof data === 'object' ? data : {};
        let result = new NodeResultResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["nodeId"] = this.nodeId;
        data["forces"] = this.forces ? this.forces.toJSON() : <any>undefined;
        data["displacements"] = this.displacements ? this.displacements.toJSON() : <any>undefined;
        super.toJSON(data);
        return data;
    }
}

export interface INodeResultResponse extends IBeamOsContractBase {
    nodeId: string;
    forces: ForcesResponse;
    displacements: DisplacementsResponse;
}

export class ForcesResponse implements IForcesResponse {
    forceAlongX!: UnitValueDto;
    forceAlongY!: UnitValueDto;
    forceAlongZ!: UnitValueDto;
    momentAboutX!: UnitValueDto;
    momentAboutY!: UnitValueDto;
    momentAboutZ!: UnitValueDto;

    constructor(data?: IForcesResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.forceAlongX = new UnitValueDto();
            this.forceAlongY = new UnitValueDto();
            this.forceAlongZ = new UnitValueDto();
            this.momentAboutX = new UnitValueDto();
            this.momentAboutY = new UnitValueDto();
            this.momentAboutZ = new UnitValueDto();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.forceAlongX = _data["forceAlongX"] ? UnitValueDto.fromJS(_data["forceAlongX"]) : new UnitValueDto();
            this.forceAlongY = _data["forceAlongY"] ? UnitValueDto.fromJS(_data["forceAlongY"]) : new UnitValueDto();
            this.forceAlongZ = _data["forceAlongZ"] ? UnitValueDto.fromJS(_data["forceAlongZ"]) : new UnitValueDto();
            this.momentAboutX = _data["momentAboutX"] ? UnitValueDto.fromJS(_data["momentAboutX"]) : new UnitValueDto();
            this.momentAboutY = _data["momentAboutY"] ? UnitValueDto.fromJS(_data["momentAboutY"]) : new UnitValueDto();
            this.momentAboutZ = _data["momentAboutZ"] ? UnitValueDto.fromJS(_data["momentAboutZ"]) : new UnitValueDto();
        }
    }

    static fromJS(data: any): ForcesResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ForcesResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["forceAlongX"] = this.forceAlongX ? this.forceAlongX.toJSON() : <any>undefined;
        data["forceAlongY"] = this.forceAlongY ? this.forceAlongY.toJSON() : <any>undefined;
        data["forceAlongZ"] = this.forceAlongZ ? this.forceAlongZ.toJSON() : <any>undefined;
        data["momentAboutX"] = this.momentAboutX ? this.momentAboutX.toJSON() : <any>undefined;
        data["momentAboutY"] = this.momentAboutY ? this.momentAboutY.toJSON() : <any>undefined;
        data["momentAboutZ"] = this.momentAboutZ ? this.momentAboutZ.toJSON() : <any>undefined;
        return data;
    }
}

export interface IForcesResponse {
    forceAlongX: UnitValueDto;
    forceAlongY: UnitValueDto;
    forceAlongZ: UnitValueDto;
    momentAboutX: UnitValueDto;
    momentAboutY: UnitValueDto;
    momentAboutZ: UnitValueDto;
}

export class UnitValueDto implements IUnitValueDto {
    value!: number;
    unit!: string;

    constructor(data?: IUnitValueDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.value = _data["value"];
            this.unit = _data["unit"];
        }
    }

    static fromJS(data: any): UnitValueDto {
        data = typeof data === 'object' ? data : {};
        let result = new UnitValueDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["value"] = this.value;
        data["unit"] = this.unit;
        return data;
    }
}

export interface IUnitValueDto {
    value: number;
    unit: string;
}

export class DisplacementsResponse implements IDisplacementsResponse {
    displacementAlongX!: UnitValueDto;
    displacementAlongY!: UnitValueDto;
    displacementAlongZ!: UnitValueDto;
    rotationAboutX!: UnitValueDto;
    rotationAboutY!: UnitValueDto;
    rotationAboutZ!: UnitValueDto;

    constructor(data?: IDisplacementsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.displacementAlongX = new UnitValueDto();
            this.displacementAlongY = new UnitValueDto();
            this.displacementAlongZ = new UnitValueDto();
            this.rotationAboutX = new UnitValueDto();
            this.rotationAboutY = new UnitValueDto();
            this.rotationAboutZ = new UnitValueDto();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.displacementAlongX = _data["displacementAlongX"] ? UnitValueDto.fromJS(_data["displacementAlongX"]) : new UnitValueDto();
            this.displacementAlongY = _data["displacementAlongY"] ? UnitValueDto.fromJS(_data["displacementAlongY"]) : new UnitValueDto();
            this.displacementAlongZ = _data["displacementAlongZ"] ? UnitValueDto.fromJS(_data["displacementAlongZ"]) : new UnitValueDto();
            this.rotationAboutX = _data["rotationAboutX"] ? UnitValueDto.fromJS(_data["rotationAboutX"]) : new UnitValueDto();
            this.rotationAboutY = _data["rotationAboutY"] ? UnitValueDto.fromJS(_data["rotationAboutY"]) : new UnitValueDto();
            this.rotationAboutZ = _data["rotationAboutZ"] ? UnitValueDto.fromJS(_data["rotationAboutZ"]) : new UnitValueDto();
        }
    }

    static fromJS(data: any): DisplacementsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new DisplacementsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["displacementAlongX"] = this.displacementAlongX ? this.displacementAlongX.toJSON() : <any>undefined;
        data["displacementAlongY"] = this.displacementAlongY ? this.displacementAlongY.toJSON() : <any>undefined;
        data["displacementAlongZ"] = this.displacementAlongZ ? this.displacementAlongZ.toJSON() : <any>undefined;
        data["rotationAboutX"] = this.rotationAboutX ? this.rotationAboutX.toJSON() : <any>undefined;
        data["rotationAboutY"] = this.rotationAboutY ? this.rotationAboutY.toJSON() : <any>undefined;
        data["rotationAboutZ"] = this.rotationAboutZ ? this.rotationAboutZ.toJSON() : <any>undefined;
        return data;
    }
}

export interface IDisplacementsResponse {
    displacementAlongX: UnitValueDto;
    displacementAlongY: UnitValueDto;
    displacementAlongZ: UnitValueDto;
    rotationAboutX: UnitValueDto;
    rotationAboutY: UnitValueDto;
    rotationAboutZ: UnitValueDto;
}

export class IdRequest implements IIdRequest {

    constructor(data?: IIdRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): IdRequest {
        data = typeof data === 'object' ? data : {};
        let result = new IdRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IIdRequest {
}

export class SectionProfileResponse implements ISectionProfileResponse {
    id!: string;
    area!: UnitValueDto;
    strongAxisMomentOfInertia!: UnitValueDto;
    weakAxisMomentOfInertia!: UnitValueDto;
    polarMomentOfInertia!: UnitValueDto;

    constructor(data?: ISectionProfileResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.area = new UnitValueDto();
            this.strongAxisMomentOfInertia = new UnitValueDto();
            this.weakAxisMomentOfInertia = new UnitValueDto();
            this.polarMomentOfInertia = new UnitValueDto();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.area = _data["area"] ? UnitValueDto.fromJS(_data["area"]) : new UnitValueDto();
            this.strongAxisMomentOfInertia = _data["strongAxisMomentOfInertia"] ? UnitValueDto.fromJS(_data["strongAxisMomentOfInertia"]) : new UnitValueDto();
            this.weakAxisMomentOfInertia = _data["weakAxisMomentOfInertia"] ? UnitValueDto.fromJS(_data["weakAxisMomentOfInertia"]) : new UnitValueDto();
            this.polarMomentOfInertia = _data["polarMomentOfInertia"] ? UnitValueDto.fromJS(_data["polarMomentOfInertia"]) : new UnitValueDto();
        }
    }

    static fromJS(data: any): SectionProfileResponse {
        data = typeof data === 'object' ? data : {};
        let result = new SectionProfileResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["area"] = this.area ? this.area.toJSON() : <any>undefined;
        data["strongAxisMomentOfInertia"] = this.strongAxisMomentOfInertia ? this.strongAxisMomentOfInertia.toJSON() : <any>undefined;
        data["weakAxisMomentOfInertia"] = this.weakAxisMomentOfInertia ? this.weakAxisMomentOfInertia.toJSON() : <any>undefined;
        data["polarMomentOfInertia"] = this.polarMomentOfInertia ? this.polarMomentOfInertia.toJSON() : <any>undefined;
        return data;
    }
}

export interface ISectionProfileResponse {
    id: string;
    area: UnitValueDto;
    strongAxisMomentOfInertia: UnitValueDto;
    weakAxisMomentOfInertia: UnitValueDto;
    polarMomentOfInertia: UnitValueDto;
}

export class CreateSectionProfileRequest implements ICreateSectionProfileRequest {
    modelId!: string;
    area!: UnitValueDto;
    strongAxisMomentOfInertia!: UnitValueDto;
    weakAxisMomentOfInertia!: UnitValueDto;
    polarMomentOfInertia!: UnitValueDto;

    constructor(data?: ICreateSectionProfileRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.area = new UnitValueDto();
            this.strongAxisMomentOfInertia = new UnitValueDto();
            this.weakAxisMomentOfInertia = new UnitValueDto();
            this.polarMomentOfInertia = new UnitValueDto();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.modelId = _data["modelId"];
            this.area = _data["area"] ? UnitValueDto.fromJS(_data["area"]) : new UnitValueDto();
            this.strongAxisMomentOfInertia = _data["strongAxisMomentOfInertia"] ? UnitValueDto.fromJS(_data["strongAxisMomentOfInertia"]) : new UnitValueDto();
            this.weakAxisMomentOfInertia = _data["weakAxisMomentOfInertia"] ? UnitValueDto.fromJS(_data["weakAxisMomentOfInertia"]) : new UnitValueDto();
            this.polarMomentOfInertia = _data["polarMomentOfInertia"] ? UnitValueDto.fromJS(_data["polarMomentOfInertia"]) : new UnitValueDto();
        }
    }

    static fromJS(data: any): CreateSectionProfileRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateSectionProfileRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["modelId"] = this.modelId;
        data["area"] = this.area ? this.area.toJSON() : <any>undefined;
        data["strongAxisMomentOfInertia"] = this.strongAxisMomentOfInertia ? this.strongAxisMomentOfInertia.toJSON() : <any>undefined;
        data["weakAxisMomentOfInertia"] = this.weakAxisMomentOfInertia ? this.weakAxisMomentOfInertia.toJSON() : <any>undefined;
        data["polarMomentOfInertia"] = this.polarMomentOfInertia ? this.polarMomentOfInertia.toJSON() : <any>undefined;
        return data;
    }
}

export interface ICreateSectionProfileRequest {
    modelId: string;
    area: UnitValueDto;
    strongAxisMomentOfInertia: UnitValueDto;
    weakAxisMomentOfInertia: UnitValueDto;
    polarMomentOfInertia: UnitValueDto;
}

export class PointLoadResponse implements IPointLoadResponse {
    id!: string;
    modelId!: string;
    nodeId!: string;
    force!: UnitValueDto;
    direction!: Vector3;

    constructor(data?: IPointLoadResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.force = new UnitValueDto();
            this.direction = new Vector3();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.modelId = _data["modelId"];
            this.nodeId = _data["nodeId"];
            this.force = _data["force"] ? UnitValueDto.fromJS(_data["force"]) : new UnitValueDto();
            this.direction = _data["direction"] ? Vector3.fromJS(_data["direction"]) : new Vector3();
        }
    }

    static fromJS(data: any): PointLoadResponse {
        data = typeof data === 'object' ? data : {};
        let result = new PointLoadResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["modelId"] = this.modelId;
        data["nodeId"] = this.nodeId;
        data["force"] = this.force ? this.force.toJSON() : <any>undefined;
        data["direction"] = this.direction ? this.direction.toJSON() : <any>undefined;
        return data;
    }
}

export interface IPointLoadResponse {
    id: string;
    modelId: string;
    nodeId: string;
    force: UnitValueDto;
    direction: Vector3;
}

export class Vector3 implements IVector3 {
    x!: number;
    y!: number;
    z!: number;

    constructor(data?: IVector3) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.x = _data["x"];
            this.y = _data["y"];
            this.z = _data["z"];
        }
    }

    static fromJS(data: any): Vector3 {
        data = typeof data === 'object' ? data : {};
        let result = new Vector3();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["x"] = this.x;
        data["y"] = this.y;
        data["z"] = this.z;
        return data;
    }
}

export interface IVector3 {
    x: number;
    y: number;
    z: number;
}

export class CreatePointLoadRequest implements ICreatePointLoadRequest {
    nodeId!: string;
    force!: UnitValueDto;
    direction!: Vector3;

    constructor(data?: ICreatePointLoadRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.force = new UnitValueDto();
            this.direction = new Vector3();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.nodeId = _data["nodeId"];
            this.force = _data["force"] ? UnitValueDto.fromJS(_data["force"]) : new UnitValueDto();
            this.direction = _data["direction"] ? Vector3.fromJS(_data["direction"]) : new Vector3();
        }
    }

    static fromJS(data: any): CreatePointLoadRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreatePointLoadRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["nodeId"] = this.nodeId;
        data["force"] = this.force ? this.force.toJSON() : <any>undefined;
        data["direction"] = this.direction ? this.direction.toJSON() : <any>undefined;
        return data;
    }
}

export interface ICreatePointLoadRequest {
    nodeId: string;
    force: UnitValueDto;
    direction: Vector3;
}

export class MomentLoadResponse implements IMomentLoadResponse {
    id!: string;
    nodeId!: string;
    torque!: UnitValueDto;
    axisDirection!: Vector3;

    constructor(data?: IMomentLoadResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.torque = new UnitValueDto();
            this.axisDirection = new Vector3();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.nodeId = _data["nodeId"];
            this.torque = _data["torque"] ? UnitValueDto.fromJS(_data["torque"]) : new UnitValueDto();
            this.axisDirection = _data["axisDirection"] ? Vector3.fromJS(_data["axisDirection"]) : new Vector3();
        }
    }

    static fromJS(data: any): MomentLoadResponse {
        data = typeof data === 'object' ? data : {};
        let result = new MomentLoadResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["nodeId"] = this.nodeId;
        data["torque"] = this.torque ? this.torque.toJSON() : <any>undefined;
        data["axisDirection"] = this.axisDirection ? this.axisDirection.toJSON() : <any>undefined;
        return data;
    }
}

export interface IMomentLoadResponse {
    id: string;
    nodeId: string;
    torque: UnitValueDto;
    axisDirection: Vector3;
}

export class CreateMomentLoadRequest implements ICreateMomentLoadRequest {
    nodeId!: string;
    torque!: UnitValueDto;
    axisDirection!: Vector3;

    constructor(data?: ICreateMomentLoadRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.torque = new UnitValueDto();
            this.axisDirection = new Vector3();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.nodeId = _data["nodeId"];
            this.torque = _data["torque"] ? UnitValueDto.fromJS(_data["torque"]) : new UnitValueDto();
            this.axisDirection = _data["axisDirection"] ? Vector3.fromJS(_data["axisDirection"]) : new Vector3();
        }
    }

    static fromJS(data: any): CreateMomentLoadRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateMomentLoadRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["nodeId"] = this.nodeId;
        data["torque"] = this.torque ? this.torque.toJSON() : <any>undefined;
        data["axisDirection"] = this.axisDirection ? this.axisDirection.toJSON() : <any>undefined;
        return data;
    }
}

export interface ICreateMomentLoadRequest {
    nodeId: string;
    torque: UnitValueDto;
    axisDirection: Vector3;
}

export class GetMomentLoadRequest implements IGetMomentLoadRequest {

    constructor(data?: IGetMomentLoadRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): GetMomentLoadRequest {
        data = typeof data === 'object' ? data : {};
        let result = new GetMomentLoadRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IGetMomentLoadRequest {
}

export class ModelResponse extends BeamOsContractBase implements IModelResponse {
    id!: string;
    name!: string;
    description!: string;
    settings!: ModelSettingsResponse;
    nodes?: NodeResponse[] | undefined;
    element1ds?: Element1DResponse[] | undefined;
    materials?: MaterialResponse[] | undefined;
    sectionProfiles?: SectionProfileResponse[] | undefined;
    pointLoads?: PointLoadResponse[] | undefined;
    momentLoads?: MomentLoadResponse[] | undefined;

    constructor(data?: IModelResponse) {
        super(data);
        if (!data) {
            this.settings = new ModelSettingsResponse();
        }
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.settings = _data["settings"] ? ModelSettingsResponse.fromJS(_data["settings"]) : new ModelSettingsResponse();
            if (Array.isArray(_data["nodes"])) {
                this.nodes = [] as any;
                for (let item of _data["nodes"])
                    this.nodes!.push(NodeResponse.fromJS(item));
            }
            if (Array.isArray(_data["element1ds"])) {
                this.element1ds = [] as any;
                for (let item of _data["element1ds"])
                    this.element1ds!.push(Element1DResponse.fromJS(item));
            }
            if (Array.isArray(_data["materials"])) {
                this.materials = [] as any;
                for (let item of _data["materials"])
                    this.materials!.push(MaterialResponse.fromJS(item));
            }
            if (Array.isArray(_data["sectionProfiles"])) {
                this.sectionProfiles = [] as any;
                for (let item of _data["sectionProfiles"])
                    this.sectionProfiles!.push(SectionProfileResponse.fromJS(item));
            }
            if (Array.isArray(_data["pointLoads"])) {
                this.pointLoads = [] as any;
                for (let item of _data["pointLoads"])
                    this.pointLoads!.push(PointLoadResponse.fromJS(item));
            }
            if (Array.isArray(_data["momentLoads"])) {
                this.momentLoads = [] as any;
                for (let item of _data["momentLoads"])
                    this.momentLoads!.push(MomentLoadResponse.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ModelResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ModelResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["description"] = this.description;
        data["settings"] = this.settings ? this.settings.toJSON() : <any>undefined;
        if (Array.isArray(this.nodes)) {
            data["nodes"] = [];
            for (let item of this.nodes)
                data["nodes"].push(item.toJSON());
        }
        if (Array.isArray(this.element1ds)) {
            data["element1ds"] = [];
            for (let item of this.element1ds)
                data["element1ds"].push(item.toJSON());
        }
        if (Array.isArray(this.materials)) {
            data["materials"] = [];
            for (let item of this.materials)
                data["materials"].push(item.toJSON());
        }
        if (Array.isArray(this.sectionProfiles)) {
            data["sectionProfiles"] = [];
            for (let item of this.sectionProfiles)
                data["sectionProfiles"].push(item.toJSON());
        }
        if (Array.isArray(this.pointLoads)) {
            data["pointLoads"] = [];
            for (let item of this.pointLoads)
                data["pointLoads"].push(item.toJSON());
        }
        if (Array.isArray(this.momentLoads)) {
            data["momentLoads"] = [];
            for (let item of this.momentLoads)
                data["momentLoads"].push(item.toJSON());
        }
        super.toJSON(data);
        return data;
    }
}

export interface IModelResponse extends IBeamOsContractBase {
    id: string;
    name: string;
    description: string;
    settings: ModelSettingsResponse;
    nodes?: NodeResponse[] | undefined;
    element1ds?: Element1DResponse[] | undefined;
    materials?: MaterialResponse[] | undefined;
    sectionProfiles?: SectionProfileResponse[] | undefined;
    pointLoads?: PointLoadResponse[] | undefined;
    momentLoads?: MomentLoadResponse[] | undefined;
}

export class ModelSettingsResponse implements IModelSettingsResponse {
    unitSettings!: UnitSettingsResponse;

    constructor(data?: IModelSettingsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.unitSettings = new UnitSettingsResponse();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.unitSettings = _data["unitSettings"] ? UnitSettingsResponse.fromJS(_data["unitSettings"]) : new UnitSettingsResponse();
        }
    }

    static fromJS(data: any): ModelSettingsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ModelSettingsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["unitSettings"] = this.unitSettings ? this.unitSettings.toJSON() : <any>undefined;
        return data;
    }
}

export interface IModelSettingsResponse {
    unitSettings: UnitSettingsResponse;
}

export class UnitSettingsResponse implements IUnitSettingsResponse {
    lengthUnit!: string;
    areaUnit!: string;
    volumeUnit!: string;
    forceUnit!: string;
    forcePerLengthUnit!: string;
    torqueUnit!: string;
    pressureUnit!: string;
    areaMomentOfInertiaUnit!: string;

    constructor(data?: IUnitSettingsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.lengthUnit = _data["lengthUnit"];
            this.areaUnit = _data["areaUnit"];
            this.volumeUnit = _data["volumeUnit"];
            this.forceUnit = _data["forceUnit"];
            this.forcePerLengthUnit = _data["forcePerLengthUnit"];
            this.torqueUnit = _data["torqueUnit"];
            this.pressureUnit = _data["pressureUnit"];
            this.areaMomentOfInertiaUnit = _data["areaMomentOfInertiaUnit"];
        }
    }

    static fromJS(data: any): UnitSettingsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new UnitSettingsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["lengthUnit"] = this.lengthUnit;
        data["areaUnit"] = this.areaUnit;
        data["volumeUnit"] = this.volumeUnit;
        data["forceUnit"] = this.forceUnit;
        data["forcePerLengthUnit"] = this.forcePerLengthUnit;
        data["torqueUnit"] = this.torqueUnit;
        data["pressureUnit"] = this.pressureUnit;
        data["areaMomentOfInertiaUnit"] = this.areaMomentOfInertiaUnit;
        return data;
    }
}

export interface IUnitSettingsResponse {
    lengthUnit: string;
    areaUnit: string;
    volumeUnit: string;
    forceUnit: string;
    forcePerLengthUnit: string;
    torqueUnit: string;
    pressureUnit: string;
    areaMomentOfInertiaUnit: string;
}

export class NodeResponse extends BeamOsContractBase implements INodeResponse {
    id!: string;
    modelId!: string;
    locationPoint!: PointResponse;
    restraint!: RestraintResponse;

    constructor(data?: INodeResponse) {
        super(data);
        if (!data) {
            this.locationPoint = new PointResponse();
            this.restraint = new RestraintResponse();
        }
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.id = _data["id"];
            this.modelId = _data["modelId"];
            this.locationPoint = _data["locationPoint"] ? PointResponse.fromJS(_data["locationPoint"]) : new PointResponse();
            this.restraint = _data["restraint"] ? RestraintResponse.fromJS(_data["restraint"]) : new RestraintResponse();
        }
    }

    static fromJS(data: any): NodeResponse {
        data = typeof data === 'object' ? data : {};
        let result = new NodeResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["modelId"] = this.modelId;
        data["locationPoint"] = this.locationPoint ? this.locationPoint.toJSON() : <any>undefined;
        data["restraint"] = this.restraint ? this.restraint.toJSON() : <any>undefined;
        super.toJSON(data);
        return data;
    }
}

export interface INodeResponse extends IBeamOsContractBase {
    id: string;
    modelId: string;
    locationPoint: PointResponse;
    restraint: RestraintResponse;
}

export class PointResponse extends BeamOsContractBase implements IPointResponse {
    xCoordinate!: UnitValueDto;
    yCoordinate!: UnitValueDto;
    zCoordinate!: UnitValueDto;

    constructor(data?: IPointResponse) {
        super(data);
        if (!data) {
            this.xCoordinate = new UnitValueDto();
            this.yCoordinate = new UnitValueDto();
            this.zCoordinate = new UnitValueDto();
        }
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.xCoordinate = _data["xCoordinate"] ? UnitValueDto.fromJS(_data["xCoordinate"]) : new UnitValueDto();
            this.yCoordinate = _data["yCoordinate"] ? UnitValueDto.fromJS(_data["yCoordinate"]) : new UnitValueDto();
            this.zCoordinate = _data["zCoordinate"] ? UnitValueDto.fromJS(_data["zCoordinate"]) : new UnitValueDto();
        }
    }

    static fromJS(data: any): PointResponse {
        data = typeof data === 'object' ? data : {};
        let result = new PointResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["xCoordinate"] = this.xCoordinate ? this.xCoordinate.toJSON() : <any>undefined;
        data["yCoordinate"] = this.yCoordinate ? this.yCoordinate.toJSON() : <any>undefined;
        data["zCoordinate"] = this.zCoordinate ? this.zCoordinate.toJSON() : <any>undefined;
        super.toJSON(data);
        return data;
    }
}

export interface IPointResponse extends IBeamOsContractBase {
    xCoordinate: UnitValueDto;
    yCoordinate: UnitValueDto;
    zCoordinate: UnitValueDto;
}

export class RestraintResponse extends BeamOsContractBase implements IRestraintResponse {
    canTranslateAlongX!: boolean;
    canTranslateAlongY!: boolean;
    canTranslateAlongZ!: boolean;
    canRotateAboutX!: boolean;
    canRotateAboutY!: boolean;
    canRotateAboutZ!: boolean;

    constructor(data?: IRestraintResponse) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.canTranslateAlongX = _data["canTranslateAlongX"];
            this.canTranslateAlongY = _data["canTranslateAlongY"];
            this.canTranslateAlongZ = _data["canTranslateAlongZ"];
            this.canRotateAboutX = _data["canRotateAboutX"];
            this.canRotateAboutY = _data["canRotateAboutY"];
            this.canRotateAboutZ = _data["canRotateAboutZ"];
        }
    }

    static fromJS(data: any): RestraintResponse {
        data = typeof data === 'object' ? data : {};
        let result = new RestraintResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["canTranslateAlongX"] = this.canTranslateAlongX;
        data["canTranslateAlongY"] = this.canTranslateAlongY;
        data["canTranslateAlongZ"] = this.canTranslateAlongZ;
        data["canRotateAboutX"] = this.canRotateAboutX;
        data["canRotateAboutY"] = this.canRotateAboutY;
        data["canRotateAboutZ"] = this.canRotateAboutZ;
        super.toJSON(data);
        return data;
    }
}

export interface IRestraintResponse extends IBeamOsContractBase {
    canTranslateAlongX: boolean;
    canTranslateAlongY: boolean;
    canTranslateAlongZ: boolean;
    canRotateAboutX: boolean;
    canRotateAboutY: boolean;
    canRotateAboutZ: boolean;
}

export class Element1DResponse implements IElement1DResponse {
    id!: string;
    modelId!: string;
    startNodeId!: string;
    endNodeId!: string;
    materialId!: string;
    sectionProfileId!: string;
    sectionProfileRotation!: UnitValueDto;

    constructor(data?: IElement1DResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.sectionProfileRotation = new UnitValueDto();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.modelId = _data["modelId"];
            this.startNodeId = _data["startNodeId"];
            this.endNodeId = _data["endNodeId"];
            this.materialId = _data["materialId"];
            this.sectionProfileId = _data["sectionProfileId"];
            this.sectionProfileRotation = _data["sectionProfileRotation"] ? UnitValueDto.fromJS(_data["sectionProfileRotation"]) : new UnitValueDto();
        }
    }

    static fromJS(data: any): Element1DResponse {
        data = typeof data === 'object' ? data : {};
        let result = new Element1DResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["modelId"] = this.modelId;
        data["startNodeId"] = this.startNodeId;
        data["endNodeId"] = this.endNodeId;
        data["materialId"] = this.materialId;
        data["sectionProfileId"] = this.sectionProfileId;
        data["sectionProfileRotation"] = this.sectionProfileRotation ? this.sectionProfileRotation.toJSON() : <any>undefined;
        return data;
    }
}

export interface IElement1DResponse {
    id: string;
    modelId: string;
    startNodeId: string;
    endNodeId: string;
    materialId: string;
    sectionProfileId: string;
    sectionProfileRotation: UnitValueDto;
}

export class MaterialResponse implements IMaterialResponse {
    id!: string;
    modulusOfElasticity!: UnitValueDto;
    modulusOfRigidity!: UnitValueDto;

    constructor(data?: IMaterialResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.modulusOfElasticity = new UnitValueDto();
            this.modulusOfRigidity = new UnitValueDto();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.modulusOfElasticity = _data["modulusOfElasticity"] ? UnitValueDto.fromJS(_data["modulusOfElasticity"]) : new UnitValueDto();
            this.modulusOfRigidity = _data["modulusOfRigidity"] ? UnitValueDto.fromJS(_data["modulusOfRigidity"]) : new UnitValueDto();
        }
    }

    static fromJS(data: any): MaterialResponse {
        data = typeof data === 'object' ? data : {};
        let result = new MaterialResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["modulusOfElasticity"] = this.modulusOfElasticity ? this.modulusOfElasticity.toJSON() : <any>undefined;
        data["modulusOfRigidity"] = this.modulusOfRigidity ? this.modulusOfRigidity.toJSON() : <any>undefined;
        return data;
    }
}

export interface IMaterialResponse {
    id: string;
    modulusOfElasticity: UnitValueDto;
    modulusOfRigidity: UnitValueDto;
}

export class CreateModelRequest implements ICreateModelRequest {
    name!: string;
    description!: string;
    settings!: PhysicalModelSettingsDto;
    id?: string | undefined;

    constructor(data?: ICreateModelRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.settings = new PhysicalModelSettingsDto();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.description = _data["description"];
            this.settings = _data["settings"] ? PhysicalModelSettingsDto.fromJS(_data["settings"]) : new PhysicalModelSettingsDto();
            this.id = _data["id"];
        }
    }

    static fromJS(data: any): CreateModelRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateModelRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["description"] = this.description;
        data["settings"] = this.settings ? this.settings.toJSON() : <any>undefined;
        data["id"] = this.id;
        return data;
    }
}

export interface ICreateModelRequest {
    name: string;
    description: string;
    settings: PhysicalModelSettingsDto;
    id?: string | undefined;
}

export class PhysicalModelSettingsDto implements IPhysicalModelSettingsDto {
    unitSettings!: UnitSettingsDtoVerbose;

    constructor(data?: IPhysicalModelSettingsDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.unitSettings = new UnitSettingsDtoVerbose();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.unitSettings = _data["unitSettings"] ? UnitSettingsDtoVerbose.fromJS(_data["unitSettings"]) : new UnitSettingsDtoVerbose();
        }
    }

    static fromJS(data: any): PhysicalModelSettingsDto {
        data = typeof data === 'object' ? data : {};
        let result = new PhysicalModelSettingsDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["unitSettings"] = this.unitSettings ? this.unitSettings.toJSON() : <any>undefined;
        return data;
    }
}

export interface IPhysicalModelSettingsDto {
    unitSettings: UnitSettingsDtoVerbose;
}

export class UnitSettingsDtoVerbose implements IUnitSettingsDtoVerbose {
    lengthUnit!: string;
    areaUnit!: string;
    volumeUnit!: string;
    areaMomentOfInertiaUnit!: string;
    forceUnit!: string;
    torqueUnit!: string;
    forcePerLengthUnit!: string;
    pressureUnit!: string;

    constructor(data?: IUnitSettingsDtoVerbose) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.lengthUnit = _data["lengthUnit"];
            this.areaUnit = _data["areaUnit"];
            this.volumeUnit = _data["volumeUnit"];
            this.areaMomentOfInertiaUnit = _data["areaMomentOfInertiaUnit"];
            this.forceUnit = _data["forceUnit"];
            this.torqueUnit = _data["torqueUnit"];
            this.forcePerLengthUnit = _data["forcePerLengthUnit"];
            this.pressureUnit = _data["pressureUnit"];
        }
    }

    static fromJS(data: any): UnitSettingsDtoVerbose {
        data = typeof data === 'object' ? data : {};
        let result = new UnitSettingsDtoVerbose();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["lengthUnit"] = this.lengthUnit;
        data["areaUnit"] = this.areaUnit;
        data["volumeUnit"] = this.volumeUnit;
        data["areaMomentOfInertiaUnit"] = this.areaMomentOfInertiaUnit;
        data["forceUnit"] = this.forceUnit;
        data["torqueUnit"] = this.torqueUnit;
        data["forcePerLengthUnit"] = this.forcePerLengthUnit;
        data["pressureUnit"] = this.pressureUnit;
        return data;
    }
}

export interface IUnitSettingsDtoVerbose {
    lengthUnit: string;
    areaUnit: string;
    volumeUnit: string;
    areaMomentOfInertiaUnit: string;
    forceUnit: string;
    torqueUnit: string;
    forcePerLengthUnit: string;
    pressureUnit: string;
}

export class IdRequestWithProperties implements IIdRequestWithProperties {

    constructor(data?: IIdRequestWithProperties) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): IdRequestWithProperties {
        data = typeof data === 'object' ? data : {};
        let result = new IdRequestWithProperties();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IIdRequestWithProperties {
}

export class ModelResponseHydrated extends BeamOsContractBase implements IModelResponseHydrated {
    id!: string;
    name!: string;
    description!: string;
    settings!: ModelSettingsResponse;
    nodes!: NodeResponse[];
    element1Ds!: Element1DResponse[];
    materials!: MaterialResponse[];
    sectionProfiles!: SectionProfileResponse[];
    pointLoads!: PointLoadResponse[];
    momentLoads!: MomentLoadResponse[];

    constructor(data?: IModelResponseHydrated) {
        super(data);
        if (!data) {
            this.settings = new ModelSettingsResponse();
            this.nodes = [];
            this.element1Ds = [];
            this.materials = [];
            this.sectionProfiles = [];
            this.pointLoads = [];
            this.momentLoads = [];
        }
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.settings = _data["settings"] ? ModelSettingsResponse.fromJS(_data["settings"]) : new ModelSettingsResponse();
            if (Array.isArray(_data["nodes"])) {
                this.nodes = [] as any;
                for (let item of _data["nodes"])
                    this.nodes!.push(NodeResponse.fromJS(item));
            }
            if (Array.isArray(_data["element1Ds"])) {
                this.element1Ds = [] as any;
                for (let item of _data["element1Ds"])
                    this.element1Ds!.push(Element1DResponse.fromJS(item));
            }
            if (Array.isArray(_data["materials"])) {
                this.materials = [] as any;
                for (let item of _data["materials"])
                    this.materials!.push(MaterialResponse.fromJS(item));
            }
            if (Array.isArray(_data["sectionProfiles"])) {
                this.sectionProfiles = [] as any;
                for (let item of _data["sectionProfiles"])
                    this.sectionProfiles!.push(SectionProfileResponse.fromJS(item));
            }
            if (Array.isArray(_data["pointLoads"])) {
                this.pointLoads = [] as any;
                for (let item of _data["pointLoads"])
                    this.pointLoads!.push(PointLoadResponse.fromJS(item));
            }
            if (Array.isArray(_data["momentLoads"])) {
                this.momentLoads = [] as any;
                for (let item of _data["momentLoads"])
                    this.momentLoads!.push(MomentLoadResponse.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ModelResponseHydrated {
        data = typeof data === 'object' ? data : {};
        let result = new ModelResponseHydrated();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["description"] = this.description;
        data["settings"] = this.settings ? this.settings.toJSON() : <any>undefined;
        if (Array.isArray(this.nodes)) {
            data["nodes"] = [];
            for (let item of this.nodes)
                data["nodes"].push(item.toJSON());
        }
        if (Array.isArray(this.element1Ds)) {
            data["element1Ds"] = [];
            for (let item of this.element1Ds)
                data["element1Ds"].push(item.toJSON());
        }
        if (Array.isArray(this.materials)) {
            data["materials"] = [];
            for (let item of this.materials)
                data["materials"].push(item.toJSON());
        }
        if (Array.isArray(this.sectionProfiles)) {
            data["sectionProfiles"] = [];
            for (let item of this.sectionProfiles)
                data["sectionProfiles"].push(item.toJSON());
        }
        if (Array.isArray(this.pointLoads)) {
            data["pointLoads"] = [];
            for (let item of this.pointLoads)
                data["pointLoads"].push(item.toJSON());
        }
        if (Array.isArray(this.momentLoads)) {
            data["momentLoads"] = [];
            for (let item of this.momentLoads)
                data["momentLoads"].push(item.toJSON());
        }
        super.toJSON(data);
        return data;
    }
}

export interface IModelResponseHydrated extends IBeamOsContractBase {
    id: string;
    name: string;
    description: string;
    settings: ModelSettingsResponse;
    nodes: NodeResponse[];
    element1Ds: Element1DResponse[];
    materials: MaterialResponse[];
    sectionProfiles: SectionProfileResponse[];
    pointLoads: PointLoadResponse[];
    momentLoads: MomentLoadResponse[];
}

export class GetModelHydratedRequest implements IGetModelHydratedRequest {

    constructor(data?: IGetModelHydratedRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): GetModelHydratedRequest {
        data = typeof data === 'object' ? data : {};
        let result = new GetModelHydratedRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IGetModelHydratedRequest {
}

export enum PreconfiguredUnits {
    N_M = 0,
    K_IN = 1,
    K_FT = 2,
}

export class CreateMaterialRequest implements ICreateMaterialRequest {
    modelId!: string;
    modulusOfElasticity!: UnitValueDto;
    modulusOfRigidity!: UnitValueDto;

    constructor(data?: ICreateMaterialRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.modulusOfElasticity = new UnitValueDto();
            this.modulusOfRigidity = new UnitValueDto();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.modelId = _data["modelId"];
            this.modulusOfElasticity = _data["modulusOfElasticity"] ? UnitValueDto.fromJS(_data["modulusOfElasticity"]) : new UnitValueDto();
            this.modulusOfRigidity = _data["modulusOfRigidity"] ? UnitValueDto.fromJS(_data["modulusOfRigidity"]) : new UnitValueDto();
        }
    }

    static fromJS(data: any): CreateMaterialRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateMaterialRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["modelId"] = this.modelId;
        data["modulusOfElasticity"] = this.modulusOfElasticity ? this.modulusOfElasticity.toJSON() : <any>undefined;
        data["modulusOfRigidity"] = this.modulusOfRigidity ? this.modulusOfRigidity.toJSON() : <any>undefined;
        return data;
    }
}

export interface ICreateMaterialRequest {
    modelId: string;
    modulusOfElasticity: UnitValueDto;
    modulusOfRigidity: UnitValueDto;
}

export class GetNodeResultsRequest implements IGetNodeResultsRequest {

    constructor(data?: IGetNodeResultsRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): GetNodeResultsRequest {
        data = typeof data === 'object' ? data : {};
        let result = new GetNodeResultsRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IGetNodeResultsRequest {
}

export class CreateNodeRequest implements ICreateNodeRequest {
    modelId!: string;
    locationPoint!: PointRequest;
    restraint?: RestraintRequest | undefined;

    constructor(data?: ICreateNodeRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.locationPoint = new PointRequest();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.modelId = _data["modelId"];
            this.locationPoint = _data["locationPoint"] ? PointRequest.fromJS(_data["locationPoint"]) : new PointRequest();
            this.restraint = _data["restraint"] ? RestraintRequest.fromJS(_data["restraint"]) : <any>undefined;
        }
    }

    static fromJS(data: any): CreateNodeRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateNodeRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["modelId"] = this.modelId;
        data["locationPoint"] = this.locationPoint ? this.locationPoint.toJSON() : <any>undefined;
        data["restraint"] = this.restraint ? this.restraint.toJSON() : <any>undefined;
        return data;
    }
}

export interface ICreateNodeRequest {
    modelId: string;
    locationPoint: PointRequest;
    restraint?: RestraintRequest | undefined;
}

export class PointRequest implements IPointRequest {
    xCoordinate!: UnitValueDto;
    yCoordinate!: UnitValueDto;
    zCoordinate!: UnitValueDto;

    constructor(data?: IPointRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.xCoordinate = new UnitValueDto();
            this.yCoordinate = new UnitValueDto();
            this.zCoordinate = new UnitValueDto();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.xCoordinate = _data["xCoordinate"] ? UnitValueDto.fromJS(_data["xCoordinate"]) : new UnitValueDto();
            this.yCoordinate = _data["yCoordinate"] ? UnitValueDto.fromJS(_data["yCoordinate"]) : new UnitValueDto();
            this.zCoordinate = _data["zCoordinate"] ? UnitValueDto.fromJS(_data["zCoordinate"]) : new UnitValueDto();
        }
    }

    static fromJS(data: any): PointRequest {
        data = typeof data === 'object' ? data : {};
        let result = new PointRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["xCoordinate"] = this.xCoordinate ? this.xCoordinate.toJSON() : <any>undefined;
        data["yCoordinate"] = this.yCoordinate ? this.yCoordinate.toJSON() : <any>undefined;
        data["zCoordinate"] = this.zCoordinate ? this.zCoordinate.toJSON() : <any>undefined;
        return data;
    }
}

export interface IPointRequest {
    xCoordinate: UnitValueDto;
    yCoordinate: UnitValueDto;
    zCoordinate: UnitValueDto;
}

export class RestraintRequest implements IRestraintRequest {
    canTranslateAlongX!: boolean;
    canTranslateAlongY!: boolean;
    canTranslateAlongZ!: boolean;
    canRotateAboutX!: boolean;
    canRotateAboutY!: boolean;
    canRotateAboutZ!: boolean;

    constructor(data?: IRestraintRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.canTranslateAlongX = _data["canTranslateAlongX"];
            this.canTranslateAlongY = _data["canTranslateAlongY"];
            this.canTranslateAlongZ = _data["canTranslateAlongZ"];
            this.canRotateAboutX = _data["canRotateAboutX"];
            this.canRotateAboutY = _data["canRotateAboutY"];
            this.canRotateAboutZ = _data["canRotateAboutZ"];
        }
    }

    static fromJS(data: any): RestraintRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RestraintRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["canTranslateAlongX"] = this.canTranslateAlongX;
        data["canTranslateAlongY"] = this.canTranslateAlongY;
        data["canTranslateAlongZ"] = this.canTranslateAlongZ;
        data["canRotateAboutX"] = this.canRotateAboutX;
        data["canRotateAboutY"] = this.canRotateAboutY;
        data["canRotateAboutZ"] = this.canRotateAboutZ;
        return data;
    }
}

export interface IRestraintRequest {
    canTranslateAlongX: boolean;
    canTranslateAlongY: boolean;
    canTranslateAlongZ: boolean;
    canRotateAboutX: boolean;
    canRotateAboutY: boolean;
    canRotateAboutZ: boolean;
}

export class ShearDiagramResponse implements IShearDiagramResponse {
    id!: string;
    element1DId!: string;
    lengthUnit!: string;
    forceUnit!: string;
    elementLength!: UnitValueDto;
    intervals!: DiagramConsistantIntervalResponse[];

    constructor(data?: IShearDiagramResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.elementLength = new UnitValueDto();
            this.intervals = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.element1DId = _data["element1DId"];
            this.lengthUnit = _data["lengthUnit"];
            this.forceUnit = _data["forceUnit"];
            this.elementLength = _data["elementLength"] ? UnitValueDto.fromJS(_data["elementLength"]) : new UnitValueDto();
            if (Array.isArray(_data["intervals"])) {
                this.intervals = [] as any;
                for (let item of _data["intervals"])
                    this.intervals!.push(DiagramConsistantIntervalResponse.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ShearDiagramResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ShearDiagramResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["element1DId"] = this.element1DId;
        data["lengthUnit"] = this.lengthUnit;
        data["forceUnit"] = this.forceUnit;
        data["elementLength"] = this.elementLength ? this.elementLength.toJSON() : <any>undefined;
        if (Array.isArray(this.intervals)) {
            data["intervals"] = [];
            for (let item of this.intervals)
                data["intervals"].push(item.toJSON());
        }
        return data;
    }
}

export interface IShearDiagramResponse {
    id: string;
    element1DId: string;
    lengthUnit: string;
    forceUnit: string;
    elementLength: UnitValueDto;
    intervals: DiagramConsistantIntervalResponse[];
}

export class DiagramConsistantIntervalResponse implements IDiagramConsistantIntervalResponse {
    startLocation!: UnitValueDto;
    endLocation!: UnitValueDto;
    polynomialCoefficients!: number[];

    constructor(data?: IDiagramConsistantIntervalResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.startLocation = new UnitValueDto();
            this.endLocation = new UnitValueDto();
            this.polynomialCoefficients = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.startLocation = _data["startLocation"] ? UnitValueDto.fromJS(_data["startLocation"]) : new UnitValueDto();
            this.endLocation = _data["endLocation"] ? UnitValueDto.fromJS(_data["endLocation"]) : new UnitValueDto();
            if (Array.isArray(_data["polynomialCoefficients"])) {
                this.polynomialCoefficients = [] as any;
                for (let item of _data["polynomialCoefficients"])
                    this.polynomialCoefficients!.push(item);
            }
        }
    }

    static fromJS(data: any): DiagramConsistantIntervalResponse {
        data = typeof data === 'object' ? data : {};
        let result = new DiagramConsistantIntervalResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["startLocation"] = this.startLocation ? this.startLocation.toJSON() : <any>undefined;
        data["endLocation"] = this.endLocation ? this.endLocation.toJSON() : <any>undefined;
        if (Array.isArray(this.polynomialCoefficients)) {
            data["polynomialCoefficients"] = [];
            for (let item of this.polynomialCoefficients)
                data["polynomialCoefficients"].push(item);
        }
        return data;
    }
}

export interface IDiagramConsistantIntervalResponse {
    startLocation: UnitValueDto;
    endLocation: UnitValueDto;
    polynomialCoefficients: number[];
}

export class CreateElement1dRequest implements ICreateElement1dRequest {
    modelId!: string;
    startNodeId!: string;
    endNodeId!: string;
    materialId!: string;
    sectionProfileId!: string;
    sectionProfileRotation?: UnitValueDto | undefined;

    constructor(data?: ICreateElement1dRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.modelId = _data["modelId"];
            this.startNodeId = _data["startNodeId"];
            this.endNodeId = _data["endNodeId"];
            this.materialId = _data["materialId"];
            this.sectionProfileId = _data["sectionProfileId"];
            this.sectionProfileRotation = _data["sectionProfileRotation"] ? UnitValueDto.fromJS(_data["sectionProfileRotation"]) : <any>undefined;
        }
    }

    static fromJS(data: any): CreateElement1dRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateElement1dRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["modelId"] = this.modelId;
        data["startNodeId"] = this.startNodeId;
        data["endNodeId"] = this.endNodeId;
        data["materialId"] = this.materialId;
        data["sectionProfileId"] = this.sectionProfileId;
        data["sectionProfileRotation"] = this.sectionProfileRotation ? this.sectionProfileRotation.toJSON() : <any>undefined;
        return data;
    }
}

export interface ICreateElement1dRequest {
    modelId: string;
    startNodeId: string;
    endNodeId: string;
    materialId: string;
    sectionProfileId: string;
    sectionProfileRotation?: UnitValueDto | undefined;
}

export class GetElement1dsRequest implements IGetElement1dsRequest {

    constructor(data?: IGetElement1dsRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): GetElement1dsRequest {
        data = typeof data === 'object' ? data : {};
        let result = new GetElement1dsRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IGetElement1dsRequest {
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}