@host = https://localhost:7120

POST {{host}}/api/node/
Content-Type: application/json

{
    "modelId": "7482fe43-5e1a-4aeb-851a-4e9ac6984c43",
    "xCoordinate" : 0,
    "yCoordinate" : 0,
    "zCoordinate" : 0,
    "lengthUnit": "Foot",
    "restraint":
    {
        "canTranslateAlongX": false,
        "canTranslateAlongY": true,
        "canTranslateAlongZ": false,
        "canRotateAboutX": true,
        "canRotateAboutY": false,
        "canRotateAboutZ": true
    }
}

# public record CreateNodeRequest(
#     string ModelId,
#     double XCoordinate,
#     double YCoordinate,
#     double ZCoordinate,
#     string? LengthUnit = null,
#     RestraintsRequest? Restraint = null);

# public record RestraintsRequest(
#     bool CanTranslateAlongX,
#     bool CanTranslateAlongY,
#     bool CanTranslateAlongZ,
#     bool CanRotationAboutX,
#     bool CanRotationAboutY,
#     bool CanRotationAboutZ);
