global using BeamOs.Common.Api;
global using BeamOs.Contracts.AnalyticalModel.Diagrams;
global using BeamOs.Contracts.AnalyticalModel.Results;
// editor contracts
global using BeamOs.Contracts.Editor;
global using BeamOs.Contracts.PhysicalModel.Element1d;
global using BeamOs.Contracts.PhysicalModel.Model;
global using BeamOs.Contracts.PhysicalModel.Node;
global using BeamOs.Contracts.PhysicalModel.PointLoad;
// events api
global using BeamOs.WebApp.Client.EditorCommands;
