global using BeamOs.Common.Api;
global using BeamOs.Contracts.AnalyticalResults;
global using BeamOs.Contracts.AnalyticalResults.AnalyticalNode;
global using BeamOs.Contracts.AnalyticalResults.Diagrams;
global using BeamOs.Contracts.AnalyticalResults.Forces;
global using BeamOs.Contracts.AnalyticalResults.Model;
global using BeamOs.Contracts.Common;
global using BeamOs.Contracts.PhysicalModel.Element1d;
global using BeamOs.Contracts.PhysicalModel.Material;
global using BeamOs.Contracts.PhysicalModel.Model;
global using BeamOs.Contracts.PhysicalModel.MomentLoad;
global using BeamOs.Contracts.PhysicalModel.Node;
global using BeamOs.Contracts.PhysicalModel.PointLoad;
global using BeamOs.Contracts.PhysicalModel.SectionProfile;
// events api
global using BeamOs.WebApp.EditorActionsAndEvents.Nodes;
