name: Build / Test / Lint

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      ContinuousIntegrationEnv: true

    # services:
    #   mssql:
    #     image: mcr.microsoft.com/mssql/server:2022-latest
    #     env:
    #       SA_PASSWORD: yourStrong(!)Password
    #       ACCEPT_EULA: 'Y'
    #     ports:
    #       - 1433:1433

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Install Azure Functions Core Tools
      run: |
        npm install -g azure-functions-core-tools@4

    - name: Build
      run: dotnet build --no-restore -c Release /p:ContinuousIntegrationEnv=true

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: './tests/**/*.info'
        targetdir: './tests/TestResults'
        reporttypes: 'lcov'
        filefilters: '-*\*.g.cs'

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./tests/TestResults/lcov.info

  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore csharpier tool
      run: dotnet tool restore

    - name: Check formatting
      run: dotnet csharpier --check .

    
