name: Build / Test / Lint

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      ContinuousIntegrationEnv: true

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Test And Collect CodeCov
      run: |
        dotnet tool install --global dotnet-coverage
        export PATH="$PATH:/root/.dotnet/tools"
        dotnet-coverage collect "dotnet test" -f cobertura -s ./CodeCov.runsettings

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: './output.cobertura.xml'
        targetdir: './tests/TestResults'
        reporttypes: 'lcov'

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./tests/TestResults/lcov.info

  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Restore csharpier tool
      run: dotnet tool restore

    - name: Check formatting
      run: dotnet csharpier --check .

    
