name: Lint

on:
  workflow_run:
    workflows: ["Build"]
    types: [requested]

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - uses: actions/checkout@v3
      - run: |
          dotnet tool restore
          dotnet csharpier --check .
