name: Lint

on:
  workflow_run:
    workflows: ["Build"]
    types: [requested]

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore csharpier tool
      run: dotnet tool restore

    - name: Check formatting
      run: dotnet csharpier --check .
